version: "3.7"

services:

  client_server:
    container_name: client_server
    image: nginx:latest
    volumes:
      - ./deploy/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: unless-stopped

  client_app:
    container_name: client_app
    build:
      context: ./
      dockerfile: ./deploy/app/Dockerfile
    volumes:
      - .:/app