version: "3.7"

services:

  client_nginx:
    container_name: client_nginx
    image: nginx:latest
    volumes:
      - ./deploy/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:3000
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./deploy/app/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - client_nginx
